from fastapi import FastAPI, Request
import requests
import os
from groq import Groq

client = Groq()

app = FastAPI()

GITLAB_TOKEN = os.getenv("GITLAB_TOKEN")


def review_code(diff):

    prompt = f"""
You are a senior DevSecOps engineer.

Analyze the following code diff and provide:

1. Severity: HIGH / MEDIUM / LOW / INFO (use 🔴 🟠 🟢 ⚪)
2. Issue: Explain briefly
3. Why it matters: Short explanation
4. Fix: What should be done
5. Auto-Fix Patch (in diff format)
6. Optimization suggestion (if any)

Code diff:
{diff}
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": "You are a concise security-focused code reviewer."},
            {"role": "user", "content": prompt}
        ]
    )

    return response.choices[0].message.content


def post_gitlab_comment(project_id, mr_iid, comment):

    url = f"https://gitlab.com/api/v4/projects/{project_id}/merge_requests/{mr_iid}/notes"

    headers = {
        "PRIVATE-TOKEN": GITLAB_TOKEN
    }

    data = {
        "body": comment
    }

    response = requests.post(url, headers=headers, data=data)

    print("Comment posted:", response.status_code)


@app.post("/webhook")
async def gitlab_webhook(request: Request):

    payload = await request.json()
    event = request.headers.get("X-Gitlab-Event")

    if event == "Merge Request Hook":

        mr = payload["object_attributes"]

        title = mr["title"]
        author = payload["user"]["name"]
        project_id = payload["project"]["id"]
        mr_iid = mr["iid"]

        print("=== Merge Request Event ===")
        print("Title:", title)
        print("Author:", author)

        url = f"https://gitlab.com/api/v4/projects/{project_id}/merge_requests/{mr_iid}/changes"

        headers = {
            "PRIVATE-TOKEN": GITLAB_TOKEN
        }

        response = requests.get(url, headers=headers)
        changes = response.json()

        print("\nChanged Files:")

        all_reviews = ""
        decision = "✅ SAFE TO MERGE"

        high_count = 0
        medium_count = 0
        low_count = 0

        for change in changes["changes"]:

            filename = change["new_path"]
            diff = change["diff"]

            if len(diff) > 5000:
                continue

            print("File:", filename)

            review = review_code(diff)

            print("\nAI Review:")
            print(review)

            all_reviews += f"\n### 📄 File: {filename}\n{review}\n"

            # Decision logic + counting
            if "🔴" in review or "HIGH" in review:
                high_count += 1
                decision = "❌ BLOCK MERGE"
            elif "🟠" in review or "MEDIUM" in review:
                medium_count += 1
                if decision != "❌ BLOCK MERGE":
                    decision = "⚠️ REVIEW REQUIRED"
            else:
                low_count += 1

        # Security score
        if high_count > 0:
            score = "3/10"
            headline = "🚨 Critical issues detected. Merge blocked."
        elif medium_count > 0:
            score = "6/10"
            headline = "⚠️ Some risks detected. Review required."
        else:
            score = "9/10"
            headline = "✅ Code looks safe."

        # Clean summary
        summary = f"""
📌 Summary
• 🔴 High: {high_count}
• 🟠 Medium: {medium_count}
• 🟢 Low: {low_count}
"""

        # Final clean formatted output
        final_comment = f"""
## 🤖 SecureMerge AI Report

{headline}

🚦 Merge Decision: {decision}  
🔐 Security Score: {score}

{summary}

---

## 📊 Detailed Review
{all_reviews}

---

🔧 Auto-Fix patches included above  
⚡ Optimization suggestions included where applicable  

✅ Generated by SecureMerge AI Agent
"""

        post_gitlab_comment(project_id, mr_iid, final_comment)

    return {"status": "received"}